server:
  port: 8001

spring:
  application:
    name: eureka-client-8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: eureka-client-8001
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"